### ISSUE TITLE
Problem with "-x265-params log-level=error" on older ffmpeg versions

### ISSUE THREAD

**Issue by Hawkers** [Niek/superview#1]
I was running ffmpeg version 4.0.2 which I had installed on my MacOS machine, but the -x265-params argument was causing the command not to execute. For backward compatibility maybe this argument isn't really necessary?

I updated to 4.1.3 and it works as expected, but this had me stumped for a little while.

**Comment by Niek** [comment]
This parameter was [added back in 2013](https://github.com/FFmpeg/FFmpeg/commit/bb6b1731eba2fac424ff8ad3003fe58b308debd1#diff-b296b37c3a806e6adea5ec62710bf9ffR261) to ffmpeg, I think it's more likely that you had a build without x265 support.

I'll add a check to determine if ffmpeg is installed and if the x264/x265 encoders are available.

**Comment by Niek** [comment]
Added in d423810

**Comment by Hawkers** [comment]
Great! Thank you!
