### ISSUE TITLE
Request: Log Verbose option

### ISSUE THREAD

**Issue by dga711** [Niek/superview#11]
When I run into an ffmpeg error I just get output like 
![image](https://user-images.githubusercontent.com/2995606/85142965-6714e200-b249-11ea-9a4f-abfb8566e3b6.png)

It would be very helpful if i could set an option to have ffmpeg log level more verbose instead of error.

I am running into this problem when converting a DNxHR video. Is this even supported? Could it be?

**Comment by Niek** [comment]
Good point, I have improved the error messages now.

**Comment by Niek** [comment]
@all-contributors please add @dga711 for ideas

**Comment by dga711** [comment]
Awesome. Thank you!
