### ISSUE TITLE
Support for NVENC

### ISSUE THREAD

**Issue by dga711** [Niek/superview#13]
When manually converting I like to use NVENC, cause its 5 times faster on my rig. It would be awesome if that would be an option with SuperView.

The FFMPEG call would look something like
`ffmpeg -vsync 0 -hwaccel cuvid -c:v h264_nvenc`

Here is an example involving processing from NVIDIA
`ffmpeg -vsync 0 –hwaccel cuvid -c:v h264_cuvid –resize 1280x720 -i input.mp4 -c:a copy -c:v h264_nvenc -b:v 5M output.mp4` from https://developer.nvidia.com/blog/nvidia-ffmpeg-transcoding-guide/

**Comment by daich** [comment]
and along the same vein, h264_qsv support please.

**Comment by Niek** [comment]
Good idea, I need to think about the best way to add it. Probably parsing ``ffmpeg -hwaccels -hide_banner`` and automatically using that if available would be the best.

**Comment by Niek** [comment]
Added to master now, can @dga711 or @daich please test?

CLI version:
``go run superview-cli.go common.go  -i input.mp4 -c h264`` (-c h264 because the input file might be h265 encoded)

GUI version:
``go run superview-gui.go common.go`` and select one of the hardware accelerated encoders

**Comment by dga711** [comment]
@Niek Good stuff! Although it seems to pick libx264 for me even if nvenc is available?

![image](https://user-images.githubusercontent.com/2995606/88920275-d92b0e80-d26c-11ea-9a6c-a162313e82c7.png)

Sadly I am not versed in Go and have the environment to debug.

**Comment by Niek** [comment]
@dga711 what is the line just above this saying? It should state which hardware accelerators are available.

**Comment by dga711** [comment]
![image](https://user-images.githubusercontent.com/2995606/88925211-82293780-d274-11ea-9e7f-45da1159713c.png)

**Comment by Niek** [comment]
Thanks for testing @dga711! I think the issue was Windows newlines, can you test the latest master again? If it still doesn't use hardware acceleration, please post the output of ``ffmpeg -hwaccels`` so I can check.

**Comment by dga711** [comment]
![image](https://user-images.githubusercontent.com/2995606/88965884-b79d4780-d2ab-11ea-829f-4fea08b79514.png)

@Niek It seems like it now tries to qsv. Which afaik is for Intel GPUs and I don't have it.

Guess it should prioritize Cuda when possible.

![image](https://user-images.githubusercontent.com/2995606/88965983-e1566e80-d2ab-11ea-8eb9-365e385f278d.png)

**Comment by Niek** [comment]
This should be resolved as of https://github.com/Niek/superview/commit/beeddb928a20628b77f321c92391df7563cad4c8

Unfortunately it's not possibly to reliably detect if your hardware supports a specific hardware encoder, so you have to manually select one with the ``-e`` option (use ``-h`` to list the available ones). Please let me know if it works now @dga711

**Comment by dga711** [comment]
@Niek Works great and is good enough for me. Thanks!

**Comment by Niek** [comment]
Thanks, closing this then

@all-contributors please add @dga711 for testing
