### ISSUE TITLE
gui ffmpeg error state 1

### ISSUE THREAD

**Issue by minzukas** [Niek/superview#17]
![error](https://user-images.githubusercontent.com/42060128/90133276-2f07b800-dd3d-11ea-8643-d49da935097e.png)
I am on 20.02.01LTS and can't get  superview to work properly.Error message attached.

**Comment by Niek** [comment]
Did you name the output file ending with ".mp4"? If not, can you try again with the mp4 extension?

**Comment by minzukas** [comment]
All files are with .MP4 extension. I am using Runcam 5 orange and the only option I got it working sofar was 4k 30fps XV with distortion correction on. 1440p 60fps gives me error. Will try some more settings.

**Comment by minzukas** [comment]
might the problem be that raw video is just too dark with low ISO and ND filter on?

**Comment by Niek** [comment]
No, it must be something with the input file. Do you have any chance to upload a (small) clip that is not working in a comment? That way I'm able to debug the issue.

**Comment by minzukas** [comment]
I can confirm superview working now with 1440p 60fps both distortion correction on and of. So either video was too dark or maybe just some unknown bug with camera or pc. Not sure, however it really works now. I suggest to close issue :)

**Comment by Niek** [comment]
Good to hear, thanks!
