### ISSUE TITLE
FFmpeg Link broken

### ISSUE THREAD

**Issue by tommaier123** [Niek/superview#20]
Hello,
The FFmpeg link doesnt work anymore. What files is it looking for and where?

**Comment by Niek** [comment]
Good point, I have updated the README with new links: https://github.com/Niek/superview#requirements

**Comment by Niek** [comment]
@all-contributors please add @tommaier123 for docs

**Comment by tommaier123** [comment]
Awesome, such a fast repy. Thanks @Niek
