### ISSUE TITLE
Cleaning up pgm files

### ISSUE THREAD

**Issue by AlfredJKwack** [Niek/superview#28]
Hi,
Great tool and really clean implementation thanks for bringing this to the community.

My only ask would be to have the CLI clean out the `x.pgm` and `y.pgm` files when encoding is completed.
Environment: MacOS 10.15.7

**Comment by Niek** [comment]
Good one! Fixed now

**Comment by Niek** [comment]
Released as https://github.com/Niek/superview/releases/tag/v0.10

**Comment by AlfredJKwack** [comment]
Thanks @Niek!
