### ISSUE TITLE
Is there a way to make the re-encoding use the GPU?

### ISSUE THREAD

**Issue by antiphotom** [Niek/superview#30]
I'm on Windows, the re-encoding is pretty CPU-intensive,  are there any switches that can be used to use the GPU if one is present, either superview itself or ffmpeg?

Great tool though!

**Comment by Niek** [comment]
Yes, you can use a different encoder:

<img width="782" alt="Screen Shot 2021-03-22 at 08 34 14" src="https://user-images.githubusercontent.com/213140/111955151-6a474200-8ae9-11eb-90e0-3d199b2ec6cf.png">

Which ones are available depends on your system and ffmpeg build.

**Comment by antiphotom** [comment]
Thanks - I used hevc_nvenc instead of "Use the same..." and it encoded much, much faster!  

Information for others:

Win 10 64 bit on Intel i7 8700k
NVidia 2060 Super
64GB RAM

**Comment by Niek** [comment]
I wish there was a way to tell ffmpeg "use the fastest hardware encoder available for this format", but unfortunately that's no possible.
