### ISSUE TITLE
Linux and OSX releases have no file extensions

### ISSUE THREAD

**Issue by AlfredJKwack** [Niek/superview#32]
Hi,

There's something amiss with the Releases. The Linux and macOS versions don't seem to have a file extension. The macOS version doesn't look like it's a dmg or tar either.

**Comment by Niek** [comment]
That's supposed to be like that - CLI programs have no file extension in \*n\*x. If you're looking for the GUI version, download `superview-gui-*.{tar.gz,dmg}`

**Comment by AlfredJKwack** [comment]
If anyone ever comes across this one. Remember `chmod +x` after downloading :-)
