### ISSUE TITLE
SuperView ERROR: open x.pgm: read-only file system

### ISSUE THREAD

**Issue by bleublancheprods** [Niek/superview#33]
![SuperView](https://user-images.githubusercontent.com/86064889/122437217-cc54fd80-cf99-11eb-9524-19ac07bc9970.png)
Hi I got this message anyone can help me please ?
MacOS Mojave 10.14.6

**Comment by Niek** [comment]
Did you copy the app in the .dmg to the Applications folder? If not, you get this error.

**Comment by bleublancheprods** [comment]
Hi, yes I have copied in the app folder but when I try to open I got this message 
![prob](https://user-images.githubusercontent.com/86064889/122546778-96faef00-d02f-11eb-8e70-a8f91a4ff4d4.png)
and when I try this command: open /Volumes/Superview/*    /don't work only work
 when the dmg is mount but I got the same ERROR message open x.pgm: read-only file system
 thanks for your help !

**Comment by Niek** [comment]
There is an existing issue about that problem, see the workaround here: https://github.com/Niek/superview/issues/26#issuecomment-803843144

Closing this issue.

**Comment by bleublancheprods** [comment]
Ok thank you problem-solved.
![Problem solved](https://user-images.githubusercontent.com/86064889/122548809-1a1d4480-d032-11eb-91f5-106d7d2d1f12.png)

**Comment by passalini** [comment]
@bleublancheprods how did you solved this issue?
I'm having the same problem here
